import { useState, useEffect } from 'react';
import { formatCurrency, formatDate } from '../../utils/formatters';
import { getDisplayName } from '../../utils/merchantDisplay';
import { transactionAPI } from '../../api';
import toast from 'react-hot-toast';

export default function TransactionModal({ transaction: tx, accountNumber, open, onClose, onDeleted }) {
  const [visible,  setVisible]  = useState(false);
  const [mounted,  setMounted]  = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [confirm,  setConfirm]  = useState(false);

  useEffect(() => {
    if (open) {
      setMounted(true);
      setConfirm(false);
      requestAnimationFrame(() => requestAnimationFrame(() => setVisible(true)));
    } else {
      setVisible(false);
      const t = setTimeout(() => setMounted(false), 260);
      return () => clearTimeout(t);
    }
  }, [open]);

  if (!mounted || !tx) return null;

  const isIncoming   = resolveDirection(tx, accountNumber) === 'in';
  const amountPrefix = isIncoming ? '+' : '−';
  const failed       = tx.status === 'failed';

  const extRef       = tx.externalReference || tx.external_reference;
  const externalName = extRef ? getDisplayName(tx) : null;

  const displayFrom  = externalName && tx.type === 'credit' ? externalName : (tx.fromName || '—');
  const displayTo    = externalName && tx.type === 'debit'  ? externalName : (tx.toName  || '—');
  const headerTitle  = isIncoming ? `From ${displayFrom}` : `To ${displayTo}`;

  const handleDownload = () => {
    const lines = [
      'COREWALLET — TRANSACTION RECEIPT',
      '═══════════════════════════════════════',
      `Reference   : ${tx.reference}`,
      `Date        : ${formatDate(tx.createdAt)}`,
      `Type        : ${tx.type.toUpperCase()}`,
      `Status      : ${tx.status.toUpperCase()}`,
      '───────────────────────────────────────',
      `From        : ${displayFrom}`,
      `Account     : ${tx.sender?.accountNumber || '—'}`,
      `To          : ${displayTo}`,
      `Account     : ${tx.receiver?.accountNumber || '—'}`,
      '───────────────────────────────────────',
      `Amount      : ${formatCurrency(tx.amount, tx.currency)}`,
      `Fee         : ${formatCurrency(0)}`,
      `Total       : ${formatCurrency(tx.amount, tx.currency)}`,
      '───────────────────────────────────────',
      tx.description ? `Note        : ${tx.description}` : '',
      `Transaction : ${tx.id}`,
      '',
      'This receipt was generated by CoreWallet.',
    ].filter(l => l !== '').join('\n');

    const blob = new Blob([lines], { type: 'text/plain' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `receipt-${tx.reference}.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success('Receipt downloaded');
  };

  const handleDelete = async () => {
    setDeleting(true);
    try {
      await transactionAPI.deleteById(tx.id);
      toast.success('Transaction removed from your history');
      onDeleted(tx.id);
      onClose();
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to delete transaction');
      setConfirm(false);
    } finally {
      setDeleting(false);
    }
  };

  const amountColor = failed ? 'text-bank-red' : isIncoming ? 'text-bank-green' : 'text-gray-900';

  return (
    <div
      className={`fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 transition-all duration-250
                  ${visible ? 'bg-black/40 backdrop-blur-sm' : 'bg-black/0 backdrop-blur-none pointer-events-none'}`}
      onClick={e => e.target === e.currentTarget && onClose()}
    >
      <div
        className={`w-full sm:max-w-md transition-all duration-250
                    ${visible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-6 sm:translate-y-4'}`}
      >
        <div className="bg-white sm:rounded-2xl overflow-hidden shadow-card-lg rounded-t-2xl">

          {/* Header */}
          <div className="flex items-center justify-between px-5 pt-5 pb-4 border-b border-gray-100">
            <div className="flex items-center gap-3">
              <div className={`w-9 h-9 rounded-xl flex items-center justify-center shrink-0 ${
                failed ? 'bg-red-50' : isIncoming ? 'bg-emerald-50' : 'bg-blue-50'
              }`}>
                {failed ? <FailIcon /> : isIncoming ? <ArrowDownIcon /> : <ArrowUpIcon />}
              </div>
              <div>
                <p className="text-gray-800 font-semibold text-sm">{headerTitle}</p>
                <p className="text-gray-400 text-xs font-mono">{tx.reference}</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="text-gray-400 hover:text-gray-600 transition-colors p-1.5 rounded-lg hover:bg-gray-100"
            >
              <XIcon />
            </button>
          </div>

          {/* Amount hero */}
          <div className="px-5 py-5 border-b border-gray-100">
            <p className="section-label mb-1">Amount</p>
            <p className={`amount-display font-bold text-3xl ${amountColor} ${failed ? 'line-through' : ''}`}>
              {amountPrefix}{formatCurrency(parseFloat(tx.amount), tx.currency)}
            </p>
            {failed && <p className="text-bank-red text-xs mt-1 font-medium">This transaction failed</p>}
          </div>

          {/* Receipt rows */}
          <div className="px-5 py-3 border-b border-gray-100 space-y-0">
            <Row label="Status"><StatusBadge status={tx.status} /></Row>
            <Row label="Type"><span className="text-gray-800 text-sm capitalize">{tx.type}</span></Row>
            <Row label="Date"><span className="text-gray-800 text-sm">{formatDate(tx.createdAt)}</span></Row>
            <Row label="From"><span className="text-gray-800 text-sm">{displayFrom}</span></Row>
            {tx.sender?.accountNumber && (
              <Row label="Sender Acc.">
                <span className="text-gray-500 text-xs font-mono">{tx.sender.accountNumber}</span>
              </Row>
            )}
            <Row label="To"><span className="text-gray-800 text-sm">{displayTo}</span></Row>
            {tx.receiver?.accountNumber && (
              <Row label="Receiver Acc.">
                <span className="text-gray-500 text-xs font-mono">{tx.receiver.accountNumber}</span>
              </Row>
            )}
            {tx.description && (
              <Row label="Note">
                <span className="text-gray-600 text-sm">{tx.description}</span>
              </Row>
            )}
            <Row label="Transaction ID">
              <span className="text-gray-400 text-[10px] font-mono break-all">{tx.id}</span>
            </Row>
          </div>

          {/* Actions */}
          <div className="px-5 py-4 space-y-2.5">
            <button
              onClick={handleDownload}
              className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl
                         bg-[#EEF4FF] text-navy border border-navy/15
                         hover:bg-[#E0EAFF] transition-all text-sm font-medium"
            >
              <DownloadIcon />
              Download Receipt
            </button>

            {!confirm ? (
              <button
                onClick={() => setConfirm(true)}
                className="w-full flex items-center justify-center gap-2 py-2.5 rounded-xl
                           text-gray-400 border border-gray-200
                           hover:bg-red-50 hover:text-bank-red hover:border-red-200
                           transition-all text-sm font-medium"
              >
                <TrashIcon />
                Remove from History
              </button>
            ) : (
              <div className="rounded-xl border border-red-200 bg-red-50 p-4">
                <p className="text-gray-700 text-sm text-center mb-3">
                  Remove this transaction from your history?
                </p>
                <div className="flex gap-2">
                  <button
                    onClick={() => setConfirm(false)}
                    disabled={deleting}
                    className="flex-1 py-2 rounded-lg text-sm text-gray-500 bg-white border border-gray-200 hover:bg-gray-50 transition-all"
                  >
                    Cancel
                  </button>
                  <button
                    onClick={handleDelete}
                    disabled={deleting}
                    className="flex-1 py-2 rounded-lg text-sm font-semibold
                               bg-bank-red/10 text-bank-red border border-bank-red/20
                               hover:bg-bank-red/20 transition-all
                               disabled:opacity-50 disabled:cursor-not-allowed
                               flex items-center justify-center gap-1.5"
                  >
                    {deleting ? <Spinner /> : null}
                    {deleting ? 'Removing…' : 'Yes, Remove'}
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
}

function resolveDirection(tx, accountNumber) {
  if (tx.type === 'credit') return 'in';
  if (tx.type === 'debit')  return 'out';
  return tx.receiver?.accountNumber === accountNumber ? 'in' : 'out';
}

const STATUS_STYLES = {
  completed: 'bg-emerald-50 text-bank-green border-emerald-200',
  pending:   'bg-amber-50 text-bank-amber border-amber-200',
  failed:    'bg-red-50 text-bank-red border-red-200',
  reversed:  'bg-gray-100 text-gray-400 border-gray-200',
};

function StatusBadge({ status }) {
  return (
    <span className={`badge border text-xs capitalize ${STATUS_STYLES[status] || STATUS_STYLES.completed}`}>
      {status}
    </span>
  );
}

function Row({ label, children }) {
  return (
    <div className="flex items-start justify-between py-2.5 border-b border-gray-50 last:border-0 gap-4">
      <span className="text-gray-400 text-xs shrink-0 pt-0.5">{label}</span>
      <div className="text-right">{children}</div>
    </div>
  );
}

function XIcon()        { return <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>; }
function ArrowDownIcon(){ return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#1A7A4A" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="5" x2="12" y2="19"/><polyline points="19 12 12 19 5 12"/></svg>; }
function ArrowUpIcon()  { return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#0072CE" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><line x1="12" y1="19" x2="12" y2="5"/><polyline points="5 12 12 5 19 12"/></svg>; }
function FailIcon()     { return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#C0392B" strokeWidth="2" strokeLinecap="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>; }
function DownloadIcon() { return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>; }
function TrashIcon()    { return <svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="3 6 5 6 21 6"/><path d="M19 6l-1 14a2 2 0 01-2 2H8a2 2 0 01-2-2L5 6"/><path d="M10 11v6M14 11v6"/><path d="M9 6V4a1 1 0 011-1h4a1 1 0 011 1v2"/></svg>; }
function Spinner()      { return <svg className="animate-spin" width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" opacity=".25"/><path d="M21 12a9 9 0 00-9-9"/></svg>; }
